### PR TITLE
Use `staticfiles_storage` to read stats file

### PR DESCRIPTION
**Pull request by robgolding**

### CODE REVIEW

**Comment by ngryman** [comment]
@robgolding So if I understand correctly, it will use Django to resolve and open the stats file instead. Is it backward compatible with the upstream repo? I'm asking so we can eventually open a PR for this.

**Comment by robgolding** [comment]
Yeah that's right. It's not backwards compatible in the current state (though we could maybe make it an option in settings). My plan would be to try and make it work first of all, and if we get there, tidy it up and make a PR upstream.

**Comment by ngryman** [comment]
@robgolding Looks like a plan. I was thinking about that too, perhaps being able to pass an open function would make it. I don't know if passing functions in settings in something usual in Python though.

**Comment by ngryman** [comment]
@robgolding Could you could publish your change to our own `pip` repository so I can test it? Thanks!

**Pull request merged**
